# yaml-language-server: $schema=https://raw.githubusercontent.com/oapi-codegen/oapi-codegen/v2.7.0/configuration-schema.json
package: server
generate:
  std-http-server: true
  models: true
output: server/openapi.gen.go
