//go:build go1.22

// Package server provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package server

import (
	"fmt"
	"net/http"

	"github.com/oapi-codegen/runtime"
)

// PostNameNameTextBody defines parameters for PostNameName.
type PostNameNameTextBody = string

// PutTagsAddrTagTextBody defines parameters for PutTagsAddrTag.
type PutTagsAddrTagTextBody = string

// PostNameNameTextRequestBody defines body for PostNameName for text/plain ContentType.
type PostNameNameTextRequestBody = PostNameNameTextBody

// PutTagsAddrTagTextRequestBody defines body for PutTagsAddrTag for text/plain ContentType.
type PutTagsAddrTagTextRequestBody = PutTagsAddrTagTextBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Root redirect
	// (GET /)
	Get(w http.ResponseWriter, r *http.Request)
	// Resolve address(es)
	// (GET /addr/{addr})
	GetAddrAddr(w http.ResponseWriter, r *http.Request, addr string)
	// Add data
	// (POST /data)
	PostData(w http.ResponseWriter, r *http.Request)
	// Get data by address
	// (GET /data/{addr})
	GetDataAddr(w http.ResponseWriter, r *http.Request, addr string)
	// Resolve a named alias to its address
	// (GET /name/{name})
	GetNameName(w http.ResponseWriter, r *http.Request, name string)
	// Set a named alias
	// (POST /name/{name})
	PostNameName(w http.ResponseWriter, r *http.Request, name string)
	// Serve a path object (autoindex or index.html)
	// (GET /path/{addr})
	GetPathAddr(w http.ResponseWriter, r *http.Request, addr string)
	// Serve a specific file from a path
	// (GET /path/{addr}/{name})
	GetPathAddrName(w http.ResponseWriter, r *http.Request, addr string, name string)
	// Get all tags for an address
	// (GET /tags/{addr})
	GetTagsAddr(w http.ResponseWriter, r *http.Request, addr string)
	// Delete a tag
	// (DELETE /tags/{addr}/{tag})
	DeleteTagsAddrTag(w http.ResponseWriter, r *http.Request, addr string, tag string)
	// Get a single tag value
	// (GET /tags/{addr}/{tag})
	GetTagsAddrTag(w http.ResponseWriter, r *http.Request, addr string, tag string)
	// Set a tag value
	// (PUT /tags/{addr}/{tag})
	PutTagsAddrTag(w http.ResponseWriter, r *http.Request, addr string, tag string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// Get operation middleware
func (siw *ServerInterfaceWrapper) Get(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Get(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAddrAddr operation middleware
func (siw *ServerInterfaceWrapper) GetAddrAddr(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "addr" -------------
	var addr string

	err = runtime.BindStyledParameterWithOptions("simple", "addr", r.PathValue("addr"), &addr, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "addr", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAddrAddr(w, r, addr)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostData operation middleware
func (siw *ServerInterfaceWrapper) PostData(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostData(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDataAddr operation middleware
func (siw *ServerInterfaceWrapper) GetDataAddr(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "addr" -------------
	var addr string

	err = runtime.BindStyledParameterWithOptions("simple", "addr", r.PathValue("addr"), &addr, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "addr", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDataAddr(w, r, addr)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetNameName operation middleware
func (siw *ServerInterfaceWrapper) GetNameName(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", r.PathValue("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetNameName(w, r, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostNameName operation middleware
func (siw *ServerInterfaceWrapper) PostNameName(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", r.PathValue("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostNameName(w, r, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPathAddr operation middleware
func (siw *ServerInterfaceWrapper) GetPathAddr(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "addr" -------------
	var addr string

	err = runtime.BindStyledParameterWithOptions("simple", "addr", r.PathValue("addr"), &addr, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "addr", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPathAddr(w, r, addr)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPathAddrName operation middleware
func (siw *ServerInterfaceWrapper) GetPathAddrName(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "addr" -------------
	var addr string

	err = runtime.BindStyledParameterWithOptions("simple", "addr", r.PathValue("addr"), &addr, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "addr", Err: err})
		return
	}

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", r.PathValue("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPathAddrName(w, r, addr, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTagsAddr operation middleware
func (siw *ServerInterfaceWrapper) GetTagsAddr(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "addr" -------------
	var addr string

	err = runtime.BindStyledParameterWithOptions("simple", "addr", r.PathValue("addr"), &addr, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "addr", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTagsAddr(w, r, addr)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteTagsAddrTag operation middleware
func (siw *ServerInterfaceWrapper) DeleteTagsAddrTag(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "addr" -------------
	var addr string

	err = runtime.BindStyledParameterWithOptions("simple", "addr", r.PathValue("addr"), &addr, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "addr", Err: err})
		return
	}

	// ------------- Path parameter "tag" -------------
	var tag string

	err = runtime.BindStyledParameterWithOptions("simple", "tag", r.PathValue("tag"), &tag, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tag", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteTagsAddrTag(w, r, addr, tag)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTagsAddrTag operation middleware
func (siw *ServerInterfaceWrapper) GetTagsAddrTag(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "addr" -------------
	var addr string

	err = runtime.BindStyledParameterWithOptions("simple", "addr", r.PathValue("addr"), &addr, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "addr", Err: err})
		return
	}

	// ------------- Path parameter "tag" -------------
	var tag string

	err = runtime.BindStyledParameterWithOptions("simple", "tag", r.PathValue("tag"), &tag, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tag", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTagsAddrTag(w, r, addr, tag)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutTagsAddrTag operation middleware
func (siw *ServerInterfaceWrapper) PutTagsAddrTag(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "addr" -------------
	var addr string

	err = runtime.BindStyledParameterWithOptions("simple", "addr", r.PathValue("addr"), &addr, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "addr", Err: err})
		return
	}

	// ------------- Path parameter "tag" -------------
	var tag string

	err = runtime.BindStyledParameterWithOptions("simple", "tag", r.PathValue("tag"), &tag, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tag", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutTagsAddrTag(w, r, addr, tag)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/{$}", wrapper.Get)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/addr/{addr}", wrapper.GetAddrAddr)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/data", wrapper.PostData)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/data/{addr}", wrapper.GetDataAddr)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/name/{name}", wrapper.GetNameName)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/name/{name}", wrapper.PostNameName)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/path/{addr}", wrapper.GetPathAddr)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/path/{addr}/{name}", wrapper.GetPathAddrName)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/tags/{addr}", wrapper.GetTagsAddr)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/tags/{addr}/{tag}", wrapper.DeleteTagsAddrTag)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/tags/{addr}/{tag}", wrapper.GetTagsAddrTag)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/tags/{addr}/{tag}", wrapper.PutTagsAddrTag)

	return m
}
